version: '3.8'

services:
  lastfm:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: lastfm-local
    container_name: lastfm-production
    environment:
      - PIPELINE=${PIPELINE:-complete}
      - MEM_LIMIT=${MEM_LIMIT:-12g}
      - JAVA_OPTS=${JAVA_OPTS:--Xmx8g -XX:+UseG1GC}
      - SPARK_PARTITIONS=${SPARK_PARTITIONS:-16}
      - SESSION_GAP_MINUTES=${SESSION_GAP_MINUTES:-20}
      - TOP_SESSIONS=${TOP_SESSIONS:-50}
      - TOP_TRACKS=${TOP_TRACKS:-10}
    mem_limit: ${MEM_LIMIT:-12g}
    cpus: ${CPU_LIMIT:-6}
    ports:
      - "${SPARK_UI_PORT:-4040}:4040"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    working_dir: /app
    command: ["${PIPELINE:-complete}"]

  lastfm-test:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: lastfm-local
    container_name: lastfm-test
    environment:
      - PIPELINE=test
      - MEM_LIMIT=4g
      - JAVA_OPTS=-Xmx2g -XX:+UseG1GC
      - SPARK_PARTITIONS=2
    mem_limit: 4g
    cpus: 2
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    working_dir: /app
    command: ["test"]
